In [1]:
import numpy as np

In [2]:
n = np.arange(10)

In [4]:
n.shape = (2, 5)

In [5]:
n

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [8]:
n[:,0]

array([0, 5])

In [20]:
np.max(n, axis=1)

array([4, 9])

In [13]:
w = np.array([["lwef", "wefef", "eferfreg"], ["sf", "ewfwef", "rr3rw"]])

In [16]:
w

array([['lwef', 'wefef', 'eferfreg'],
       ['sf', 'ewfwef', 'rr3rw']], dtype='<U8')

In [18]:
max()

UFuncTypeError: ufunc 'maximum' did not contain a loop with signature matching types (dtype('<U8'), dtype('<U8')) -> None